# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.terrain_grid_map import TerrainGridMap  # noqa: F401,E501
from swagger_server import util


class TerrainGrid(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, map: TerrainGridMap=None):  # noqa: E501
        """TerrainGrid - a model defined in Swagger

        :param map: The map of this TerrainGrid.  # noqa: E501
        :type map: TerrainGridMap
        """
        self.swagger_types = {
            'map': TerrainGridMap
        }

        self.attribute_map = {
            'map': 'map'
        }
        self._map = map

    @classmethod
    def from_dict(cls, dikt) -> 'TerrainGrid':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TerrainGrid of this TerrainGrid.  # noqa: E501
        :rtype: TerrainGrid
        """
        return util.deserialize_model(dikt, cls)

    @property
    def map(self) -> TerrainGridMap:
        """Gets the map of this TerrainGrid.


        :return: The map of this TerrainGrid.
        :rtype: TerrainGridMap
        """
        return self._map

    @map.setter
    def map(self, map: TerrainGridMap):
        """Sets the map of this TerrainGrid.


        :param map: The map of this TerrainGrid.
        :type map: TerrainGridMap
        """

        self._map = map
